<?php
    $token = $_REQUEST['token'];
    $q = mysqli_query($con, "select * from tblreset where token = '$token' and used = '0'");
    $num = mysqli_num_rows($q);
    if($num > 0)
    {
        $qf = mysqli_fetch_array($q);
        $email = $qf['email'];
        $pword2 = rand(100000,999999);
		$pword = md5($pword2);
        $q = mysqli_query($con, "update tblusers set fldPassword = '$pword' where fldEmail = '$email'");
        $q = mysqli_query($con, "update tblreset set used = '1' where email = '$email'");
        
        $to = $email;
            $subject = "LTN Events Account Password Reset";
            $message = "This email is automatically generated by the system.<br><br>Your password has been successfully reset.<br><br>Your new password is: <u>". $pword2 . "</u>";
            $headers = "MIME-Version: 1.0" . "\r\n";
            $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
            $headers .= 'From: ltneventstest@gmail.com' . "\r\n" . 
                        'Reply-To: ltneventstest@gmail.com' . "\r\n" .
                        'X-Mailer: PHP/' . phpversion();
            mail($to, $subject, $message, $headers);
            echo "<script>alert('Password has been reset! Please check your email.');window.location='/index.php'</script>";
        
    }
    else
    {
        echo "<script>alert('Token expired or mismatch!');window.location='/index.php'</script>";
    }
    

?>